"""
This simple flow attempts to prompt a weekly release by opening a PR from dev -> master every Monday.

If for any reason the PR fails to open, the Flow attempts to open an issue alerting the team, with
relevant debug information.
"""
import datetime
import pendulum
import random

from prefect import Flow, task
from prefect.environments.storage import Docker
from prefect.triggers import any_failed
from prefect.schedules import IntervalSchedule
from prefect.tasks.github import CreateGitHubPR, OpenGitHubIssue, CreateBranch


branch_task = CreateBranch(base="dev", repo="PrefectHQ/cloud")

body = (
    "Autogenerated PR for the weekly cloud release\n\n"
    'Release Checklist: '
    '- [ ] Update changelog'
    '- [ ] Verify the pinned version of Prefect Core in master'
    '- [ ] Merge release branch into master'
    '- [ ] Tag this merge commit on master'
    '- [ ] Cut a new release of Cloud'
    '- [ ] Redeploy Staging'
)

pr_task = CreateGitHubPR(
    name="Open PR to master",
    repo="PrefectHQ/cloud",
    base="master",
    title="Cloud Release",
    body=body,
    max_retries=1,
    retry_delay=datetime.timedelta(minutes=1),
)


@task(trigger=any_failed)
def prepare_exception(exc):
    return repr(exc)


@task(name="new-branch-name")
def create_branch_name():
    return "master-release-{}".format(random.random())


issue_task = OpenGitHubIssue(
    name="Open Release Issue",
    repo="PrefectHQ/cloud",
    title="Release Cycle is Broken",
    labels=["release", "bug"],
)


biweekly_schedule = IntervalSchedule(
    start_date=pendulum.parse("2019-03-11", tz="US/Eastern"),
    interval=datetime.timedelta(days=7),
)
storage = Docker(
    prefect_version="master",
    base_image="python:3.6",
    registry_url="gcr.io/prefect-dev/flows/",
)


with Flow(
    "Biweekly Cloud Release", storage=storage, schedule=biweekly_schedule
) as flow:
    new_branch = branch_task(branch_name=create_branch_name)
    new_pr = pr_task(head=create_branch_name, upstream_tasks=[new_branch])
    exc = prepare_exception(new_pr)  # will only run if new_pr fails in some way
    issue = issue_task(body=exc)


flow.set_reference_tasks([new_pr])
