aliases:
  - &configure_google_cloud
    run:
      name: Configure Google Cloud
      command: |
        echo $STAGING_GOOGLE_APPLICATION_CREDENTIALS > ~/staging-credentials.json
        echo 'export GOOGLE_APPLICATION_CREDENTIALS=~/staging-credentials.json' >> $BASH_ENV

  - &install_docker
    run:
      name: Install Docker client
      command: |
        set -x
        VER="18.09.3"
        curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
        tar -xz -C /tmp -f /tmp/docker-$VER.tgz
        mv /tmp/docker/* /usr/bin

setup_gcloud_sdk: &setup_gcloud_sdk
  name: Set up Google Cloud SDK
  command: |
    echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > key.json
    gcloud auth activate-service-account --key-file key.json
    gcloud config set compute/zone $GCLOUD_ZONE
    gcloud config set project $GCLOUD_PROJECT

version: 2
jobs:
  test:
    docker:
      - image: python:3.6

    steps:
      - checkout
      - run:
          name: Set Google credentials
          command: |
            echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > key.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=key.json' >> $BASH_ENV
      - run:
          name: Install Marvin
          command: |
            pip install .
      - run:
          name: Test Marvin
          command: |
            pytest -v

  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      - run: *setup_gcloud_sdk
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            gcloud auth configure-docker
            docker build -t gcr.io/$GCLOUD_PROJECT/marvin:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image
          command: docker push gcr.io/$GCLOUD_PROJECT/marvin:$CIRCLE_SHA1

  deploy:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      - run: *setup_gcloud_sdk
      - run: gcloud container clusters get-credentials $GCLOUD_GKE_CLUSTER
      - run:
          name: Add Slack token to Kubernetes
          command: |
            echo -n "$MONDAY_API_TOKEN" > mondaytoken.txt
            kubectl delete secret mondaytoken --ignore-not-found
            kubectl create secret generic mondaytoken --from-file=./mondaytoken.txt
            echo -n "$PREFECT__CLOUD__AUTH_TOKEN" > prefectauthtoken.txt
            kubectl delete secret prefectauthtoken --ignore-not-found
            kubectl create secret generic prefectauthtoken --from-file=./prefectauthtoken.txt
            echo -n "$GITHUB_VALIDATION_TOKEN" > githubvalidationtoken.txt
            kubectl delete secret githubvalidationtoken --ignore-not-found
            kubectl create secret generic githubvalidationtoken --from-file=./githubvalidationtoken.txt
            echo -n "$MARVIN_ACCESS_TOKEN" > marvinaccesstoken.txt
            kubectl delete secret marvinaccesstoken --ignore-not-found
            kubectl create secret generic marvinaccesstoken --from-file=./marvinaccesstoken.txt
            echo -n "$SLACK_TOKEN" > slacktoken.txt
            kubectl delete secret slacktoken --ignore-not-found
            kubectl create secret generic slacktoken --from-file=./slacktoken.txt
            echo -n "$SLACK_OAUTH_TOKEN" > slackoauthtoken.txt
            kubectl delete secret slackoauthtoken --ignore-not-found
            kubectl create secret generic slackoauthtoken --from-file=./slackoauthtoken.txt
            echo -n "$SLACK_VALIDATION_TOKEN" > slackvalidationtoken.txt
            kubectl delete secret slackvalidationtoken --ignore-not-found
            kubectl create secret generic slackvalidationtoken --from-file=./slackvalidationtoken.txt
            echo -n "$PUBLIC_VALIDATION_TOKEN" > publicvalidationtoken.txt
            kubectl delete secret publicvalidationtoken --ignore-not-found
            kubectl create secret generic publicvalidationtoken --from-file=./publicvalidationtoken.txt
            echo -n "$MARVIN_PUBLIC_OAUTH_TOKEN" > marvinpublicoauthtoken.txt
            kubectl delete secret marvinpublicoauthtoken --ignore-not-found
            kubectl create secret generic marvinpublicoauthtoken --from-file=./marvinpublicoauthtoken.txt
            echo -n "$MARVIN_PUBLIC_TOKEN" > marvinpublictoken.txt
            kubectl delete secret marvinpublictoken --ignore-not-found
            kubectl create secret generic marvinpublictoken --from-file=./marvinpublictoken.txt
            echo -n "$CIRCLE_SHA1" > gitsha.txt
            kubectl delete secret gitsha --ignore-not-found
            kubectl create secret generic gitsha --from-file=./gitsha.txt
      - run:
          name: Deploy Marvin
          command: |
            sed -i  "s/\${IMAGE_TAG}/$CIRCLE_SHA1/g" kubernetes/deployment.yml
            kubectl apply -f kubernetes/deployment.yml

  deploy_staging_flows:
    docker:
      - image: python:3.7

    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - *install_docker
      - *configure_google_cloud
      - run:
          name: Install Prefect
          command: pip install "prefect[gcp]" google-cloud-firestore
      - run:
          name: Deploy standup flow
          command: python prefect/daily_standup_post.py

workflows:
  version: 2
  deploy_flows:
    jobs:
      - deploy_staging_flows

  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - build
