apiVersion: apps/v1
kind: Deployment
metadata:
  name: marvin-deployment
  labels:
    app: marvin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marvin
  template:
    metadata:
      labels:
        app: marvin
    spec:
      containers:
      - name: marvin
        image: registry.gitlab.com/prefect/marvin
        imagePullPolicy: Always
      imagePullSecrets:
        - name: registry.gitlab.com
