apiVersion: apps/v1
kind: Deployment
metadata:
  name: marvin-deployment
  labels:
    app: marvin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marvin
  template:
    metadata:
      labels:
        app: marvin
    spec:
      containers:
      - name: marvin
        image: gcr.io/prefect-marvin/marvin:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: PREFECT__CLOUD__GRAPHQL
            value: "https://api-staging.prefect.io/"
          - name: PREFECT__CLOUD__AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: prefectauthtoken
                key: prefectauthtoken.txt
          - name: GITHUB_VALIDATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: githubvalidationtoken
                key: githubvalidationtoken.txt
          - name: MONDAY_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: mondaytoken
                key: mondaytoken.txt
          - name: MARVIN_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: marvinaccesstoken
                key: marvinaccesstoken.txt
          - name: MARVIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: slacktoken
                key: slacktoken.txt
          - name: MARVIN_OAUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: slackoauthtoken
                key: slackoauthtoken.txt
          - name: SLACK_VALIDATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: slackvalidationtoken
                key: slackvalidationtoken.txt
          - name: PUBLIC_VALIDATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: publicvalidationtoken
                key: publicvalidationtoken.txt
          - name: MARVIN_PUBLIC_OAUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: marvinpublicoauthtoken
                key: marvinpublicoauthtoken.txt
          - name: MARVIN_PUBLIC_TOKEN
            valueFrom:
              secretKeyRef:
                name: marvinpublictoken
                key: marvinpublictoken.txt
          - name: GIT_SHA
            valueFrom:
              secretKeyRef:
                name: gitsha
                key: gitsha.txt

