---
name: Marvin Pull Request Test
permissions: {}
on:
  pull_request:
    branches:
      - master

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

jobs:
  python-tests:
    env:
      "MARVIN_GITHUB_ACCESS_TOKEN": ${{ secrets.MARVIN_GITHUB_ACCESS_TOKEN }},
      "MARVIN_GITHUB_VALIDATION_TOKEN": ${{ secrets.MARVIN_GITHUB_VALIDATION_TOKEN }},
      "MARVIN_ID": ${{ secrets.MARVIN_ID }},
      "MARVIN_MONDAY_API_TOKEN": ${{ secrets.MARVIN_MONDAY_API_TOKEN }},
      "MARVIN_PUBLIC_SLACK_OAUTH_TOKEN": ${{ secrets.MARVIN_PUBLIC_SLACK_OAUTH_TOKEN }},
      "MARVIN_PUBLIC_SLACK_TOKEN": ${{ secrets.MARVIN_PUBLIC_SLACK_TOKEN }},
      "MARVIN_PUBLIC_SLACK_VALIDATION_TOKEN": ${{ secrets.MARVIN_PUBLIC_SLACK_VALIDATION_TOKEN }},
      "MARVIN_SLACK_OAUTH_TOKEN": ${{ secrets.MARVIN_SLACK_OAUTH_TOKEN }},
      "MARVIN_SLACK_TOKEN": ${{ secrets.MARVIN_SLACK_TOKEN }},
      "MARVIN_SLACK_VALIDATION_TOKEN": ${{ secrets.MARVIN_SLACK_VALIDATION_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/511611806264/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: marvin-pr-main@prefect-org-github-actions.iam.gserviceaccount.com
          project_id: prefect-marvin

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "pip"
          cache-dependency-path: "requirements*.txt"

      - name: Install Marvin
        run: pip install -e .

      - name: Run Tests
        run: pytest -v

  test-build-marvin-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/511611806264/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: marvin-pr-main@prefect-org-github-actions.iam.gserviceaccount.com

      - name: Configure Google Cloud credential helper
        run: gcloud auth configure-docker --quiet gcr.io

      - name: Build Marvin image
        run: docker build --rm=false -t gcr.io/prefect-marvin/marvin/${COMMIT_SHA} .
