---
name: Marvin Pull Request Test

on:
  pull_request:
    branches:
      - master

# Limit concurrency by workflow/branch combination.
#
# For builds, pushing additional changes to the
# branch will cancel prior in-progress and pending builds.
#
# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Do not grant jobs any permissions by default
permissions: {}

jobs:
  python_tests:
    env:
      "MARVIN_GITHUB_ACCESS_TOKEN": ${{ secrets.MARVIN_GITHUB_ACCESS_TOKEN }},
      "MARVIN_GITHUB_VALIDATION_TOKEN": ${{ secrets.MARVIN_GITHUB_VALIDATION_TOKEN }},
      "MARVIN_ID": ${{ secrets.MARVIN_ID }},
      "MARVIN_MONDAY_API_TOKEN": ${{ secrets.MARVIN_MONDAY_API_TOKEN }},
      "MARVIN_PUBLIC_SLACK_OAUTH_TOKEN": ${{ secrets.MARVIN_PUBLIC_SLACK_OAUTH_TOKEN }},
      "MARVIN_PUBLIC_SLACK_TOKEN": ${{ secrets.MARVIN_PUBLIC_SLACK_TOKEN }},
      "MARVIN_PUBLIC_SLACK_VALIDATION_TOKEN": ${{ secrets.MARVIN_PUBLIC_SLACK_VALIDATION_TOKEN }},
      "MARVIN_SLACK_OAUTH_TOKEN": ${{ secrets.MARVIN_SLACK_OAUTH_TOKEN }},
      "MARVIN_SLACK_TOKEN": ${{ secrets.MARVIN_SLACK_TOKEN }},
      "MARVIN_SLACK_VALIDATION_TOKEN": ${{ secrets.MARVIN_SLACK_VALIDATION_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      # required to read from the repo
      contents: read
      # required to obtain Google Cloud service account credentials
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.GHA_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: marvin-pr-main@prefect-org-github-actions.iam.gserviceaccount.com

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: Install Marvin
        run: pip install -e .

      - name: Run Tests
        run: pytest -v

  test_build_push_image:
    runs-on: ubuntu-latest
    permissions:
      # required to read from the repo
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # neccessary in order to checkout current branch
          fetch-depth: 0

      - name: Get image version
        run: |
          git switch "${{ github.head_ref }}"
          short_sha=$(git rev-parse --short=7 HEAD)
          echo "SHORT_SHA=${short_sha}" >> $GITHUB_ENV

      - name: Build Marvin image
        run: docker build --rm=false -t gcr.io/prefect-marvin/marvin:${{ env.SHORT_SHA }} .
