---
name: Marvin Build and Push
permissions: {}
on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/511611806264/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: marvin-general-main@prefect-org-github-actions.iam.gserviceaccount.com
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "pip"
          cache-dependency-path: "requirements*.txt"
      - name: install marvin
        run: pip install -e .
      - name: lint
        run: black --check .
      - name: run tests
        run: pytest -v
